version: '3.7'
services:
  client:
    image: yolo-client:v1
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    stdin_open: true
    networks:
      - frontend_network

  backend:
    image: yolo-backend:v1
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    networks:
      - frontend_network
      - backend_network
  
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - backend_network

networks:
  frontend_network:
  backend_network:
